import type {
  Service,
  Portfolio,
  BlogPost,
  JobPost,
  PricePlan,
  Page,
} from "./types";

export const mockPages: Page[] = [
  {
    id: "1",
    name: "Home",
    title: "Transform Your Business with Cutting-Edge IT Solutions",
    content:
      "We deliver innovative web development, mobile apps, cloud solutions, and AI automation to help your business thrive in the digital age.",
    slug: "home",
    metaDescription:
      "Leading IT services company specializing in web development, mobile apps, cloud solutions, and AI automation.",
    published: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "2",
    name: "About",
    title: "About TechFlow Solutions",
    content:
      "We are a team of passionate developers and designers committed to delivering exceptional IT solutions.",
    slug: "about",
    metaDescription:
      "Learn about TechFlow Solutions - our mission, vision, and expert team.",
    published: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
];

export const mockServices: Service[] = [
  {
    id: "1",
    title: "Web Development",
    description:
      "Modern, responsive web applications built cutting-edge technologies.",
    icon: "Code",
    features: [
      "Responsive Design",
      "SEO Optimization",
      "Performance Optimization",
      "Modern Frameworks",
    ],
    technologies: ["React", "Next.js", "TypeScript", "Tailwind CSS"],
    pricing: { starting: 2500, currency: "USD" },
    category: "web",
    published: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "2",
    title: "App Development",
    description:
      "Native and cross-platform mobile applications for iOS and Android.",
    icon: "Smartphone",
    features: [
      "Cross-platform",
      "Native Performance",
      "App Store Optimization",
      "Push Notifications",
    ],
    technologies: ["React Native", "Flutter", "Swift", "Kotlin"],
    pricing: { starting: 5000, currency: "USD" },
    category: "mobile",
    published: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "3",
    title: "Cloud Solutions",
    description:
      "Scalable cloud infrastructure and DevOps solutions on AWS and other platforms.",
    icon: "Cloud",
    features: [
      "Auto Scaling",
      "Load Balancing",
      "CI/CD Pipelines",
      "Monitoring",
    ],
    technologies: ["AWS", "Docker", "Kubernetes", "Terraform"],
    pricing: { starting: 3000, currency: "USD" },
    category: "cloud",
    published: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "4",
    title: "AI & Automation",
    description:
      "Intelligent chatbots, AI integrations, and business process automation.",
    icon: "Bot",
    features: [
      "Natural Language Processing",
      "Machine Learning",
      "Process Automation",
      "Data Analytics",
    ],
    technologies: ["Python", "TensorFlow", "OpenAI", "LangChain"],
    pricing: { starting: 4000, currency: "USD" },
    category: "ai",
    published: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
];

export const mockPortfolio: Portfolio[] = [
  {
    id: "1",
    title: "SDL Logistics Management System",
    description: "End-to-end logistics management solution",
    longDescription:
      "SDL is a comprehensive logistics management system designed to streamline parcel tracking, driver assignments, route optimization, and real-time delivery updates. Built for efficiency, transparency, and scalability, it supports multi-tenant operations and integrates seamlessly with mobile apps for drivers and customers.",
    techStack: [
      "Next.js",
      "TypeScript",
      "Node.js",
      "MongoDB",
      "Tailwind CSS",
      "Socket.IO",
    ],
    imageUrl: "/sdl-report.jpg",
    projectUrl: "https://safedispatchlogistics.com",
    category: "web",
    client: "SDL Operations",
    duration: "6 months",
    results: [
      { metric: "Delivery Tracking Accuracy", value: "99.8%" },
      { metric: "Route Optimization Efficiency", value: "+35%" },
      { metric: "Customer Satisfaction", value: "+50%" },
    ],
    featured: true,
    published: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "2",
    title: "Healthcare Management System",
    description: "Comprehensive healthcare management solution",
    longDescription:
      "A HIPAA-compliant healthcare management system with patient records, appointment scheduling, and telemedicine capabilities.",
    techStack: ["React", "Node.js", "MongoDB", "Socket.io", "AWS"],
    imageUrl: "/placeholder.svg?height=400&width=600",
    category: "saas",
    client: "MedTech Solutions",
    duration: "6 months",
    results: [
      { metric: "Patient Satisfaction", value: "95%" },
      { metric: "Processing Time", value: "-70%" },
      { metric: "Cost Reduction", value: "40%" },
    ],
    featured: true,
    published: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
];

export const mockBlogPosts: BlogPost[] = [
  {
    id: "1",
    title: "The Future of Web Development in 2024",
    slug: "future-web-development-2024",
    excerpt:
      "Explore the latest trends and technologies shaping the future of web development.",
    content:
      "Web development continues to evolve at a rapid pace. In 2024, we're seeing exciting developments in AI integration, serverless architectures, and progressive web apps...",
    imageUrl: "/placeholder.svg?height=300&width=500",
    author: {
      name: "Sarah Johnson",
      avatar: "/placeholder.svg?height=100&width=100",
      bio: "Senior Full Stack Developer with 8+ years of experience",
    },
    tags: ["Web Development", "Technology", "Trends"],
    category: "Technology",
    readTime: 5,
    published: true,
    featured: true,
    publishedAt: "2024-01-15T00:00:00Z",
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "2",
    title: "Building Scalable Mobile Apps with React Native",
    slug: "scalable-mobile-apps-react-native",
    excerpt:
      "Learn best practices for building performant and scalable mobile applications.",
    content:
      "React Native has become a popular choice for cross-platform mobile development. Here are the key strategies for building scalable applications...",
    imageUrl: "/placeholder.svg?height=300&width=500",
    author: {
      name: "Mike Chen",
      avatar: "/placeholder.svg?height=100&width=100",
      bio: "Mobile App Specialist and React Native Expert",
    },
    tags: ["Mobile Development", "React Native", "Performance"],
    category: "Mobile",
    readTime: 7,
    published: true,
    featured: false,
    publishedAt: "2024-01-10T00:00:00Z",
    createdAt: "2024-01-10T00:00:00Z",
    updatedAt: "2024-01-10T00:00:00Z",
  },
];

export const mockJobPosts: JobPost[] = [
  {
    id: "1",
    title: "Senior Full Stack Developer",
    department: "Engineering",
    location: "Remote / San Francisco",
    type: "full-time",
    description:
      "We are looking for a Senior Full Stack Developer to join our growing team and help build cutting-edge web applications.",
    requirements: [
      "5+ years of experience in full stack development",
      "Proficiency in React, Node.js, and TypeScript",
      "Experience with cloud platforms (AWS, GCP, or Azure)",
      "Strong understanding of database design and optimization",
    ],
    responsibilities: [
      "Design and develop scalable web applications",
      "Collaborate with cross-functional teams",
      "Mentor junior developers",
      "Participate in code reviews and technical discussions",
    ],
    skills: ["React", "Node.js", "TypeScript", "AWS", "PostgreSQL"],
    experience: "5+ years",
    salary: { min: 120000, max: 180000, currency: "USD" },
    benefits: [
      "Health Insurance",
      "Dental & Vision",
      "401k Matching",
      "Flexible PTO",
      "Remote Work",
    ],
    applyUrl: "/careers/apply/1",
    published: true,
    featured: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "2",
    title: "UI/UX Designer",
    department: "Design",
    location: "New York / Remote",
    type: "full-time",
    description:
      "Join our design team to create beautiful and intuitive user experiences for our clients.",
    requirements: [
      "3+ years of UI/UX design experience",
      "Proficiency in Figma and Adobe Creative Suite",
      "Strong portfolio demonstrating design thinking",
      "Experience with user research and testing",
    ],
    responsibilities: [
      "Create wireframes, prototypes, and high-fidelity designs",
      "Conduct user research and usability testing",
      "Collaborate with developers and product managers",
      "Maintain design systems and style guides",
    ],
    skills: ["Figma", "Adobe Creative Suite", "Prototyping", "User Research"],
    experience: "3+ years",
    salary: { min: 90000, max: 130000, currency: "USD" },
    benefits: [
      "Health Insurance",
      "Dental & Vision",
      "401k Matching",
      "Professional Development Budget",
    ],
    applyUrl: "/careers/apply/2",
    published: true,
    featured: false,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
];

export const mockPricePlans: PricePlan[] = [
  {
    id: "1",
    name: "Starter Website",
    description: "Perfect for small businesses and startups",
    price: 2500,
    currency: "USD",
    billing: "one-time",
    features: [
      "Responsive Design",
      "Up to 5 Pages",
      "Contact Form",
      "SEO Optimization",
      "Mobile Friendly",
      "3 Months Support",
    ],
    limitations: ["No E-commerce", "Basic Analytics"],
    popular: false,
    ctaText: "Get Started",
    ctaUrl: "/quote?plan=starter",
    category: "web",
    published: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "2",
    name: "Professional Website",
    description: "Ideal for growing businesses",
    price: 5000,
    currency: "USD",
    billing: "one-time",
    features: [
      "Custom Design",
      "Up to 15 Pages",
      "CMS Integration",
      "Advanced SEO",
      "Analytics Setup",
      "E-commerce Ready",
      "6 Months Support",
    ],
    popular: true,
    ctaText: "Most Popular",
    ctaUrl: "/quote?plan=professional",
    category: "web",
    published: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "3",
    name: "Enterprise Solution",
    description: "For large organizations with complex needs",
    price: 15000,
    currency: "USD",
    billing: "one-time",
    features: [
      "Fully Custom Development",
      "Unlimited Pages",
      "Advanced Integrations",
      "Performance Optimization",
      "Security Audit",
      "Training & Documentation",
      "12 Months Support",
    ],
    popular: false,
    ctaText: "Contact Sales",
    ctaUrl: "/contact?plan=enterprise",
    category: "web",
    published: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
];
